<?php /** @noinspection PhpInconsistentReturnPointsInspection */

/**
 * Created by PhpStorm.
 * User: Admin
 * Date: 2019/7/11
 * Time: 10:13
 */
namespace app\forum\controller;
use app\forum\model\FriendModel;
use app\forum\Traits\CURD;
use app\forum\Traits\OutMsg;
use app\forum\Traits\User;
use app\forum\Traits\Note;
use think\facade\Request;

class Friend extends Base{

	/**
	 * @var $data
	 * 用户信息
	 */
	protected $data;

	/**
	 * @var $model
	 * 公共模型
	 */
	protected $model;

	/**
	 * @var $classify
	 * 分类
	 */
	protected $classify;

	/**
	 * @var $param
	 * 请求参数
	 */
	protected $param;

	/**
	 * 初始化
	 */
	public function initialize()
	{
		parent::initialize(); // TODO: Change the autogenerated stub
		try{
			$data = User::dataInfo();
			$this->model = new FriendModel( $data );
			$this->data = $data;
			$this->classify = Note::classify();
			$this->param = CURD::PurificationParam();
		}catch (\Exception $e){
			$this->error( $e->getMessage() );
		}
	}

	/**
	 * @param $data
	 * @return FriendModel
	 * @throws \Exception
	 */
	public function model($data){
		return new FriendModel($data);
	}

	public function index(){
		try{
			return view('index',[
				'title' =>  '我的好友',
				'classify'  =>  $this->classify,
				'data'  =>  $this->data
			]);
		}catch (\Exception $e){
			$this->error( $e->getMessage() );
		}
	}

	/**
	 * @return mixed|\think\response\Json|void
	 * @throws \Exception
	 * 我的好友
	 */
	public function friend(){
		try{
			if (Request::isGet()){
				$friendList = $this->model($this->data)->friend();
				return $friendList;
			}
		}catch (\Exception $e){
			return OutMsg::outAbnormalMsg( $e->getMessage() );
		}
	}

	/**
	 * @return mixed|\think\response\Json
	 * @throws \Exception
	 * 搜索用户返回信息
	 */
	public function searchFriend(){
		try{
			if (Request::isPost()){
				$data = $this->param;
				$friendInfo = $this->model($this->data)->friendInfo($data);
				return $friendInfo;
			}
		}catch (\Exception $e){
			return OutMsg::outAbnormalMsg( $e->getMessage() );
		}
	}

	/**
	 * @return mixed|\think\response\Json|void
	 * @throws \Exception
	 * 添加好友
	 */
	public function addFriend(){
		try{
			if (Request::isGet()){
				$friend = input('get.friend');
				$Message = $this->model($this->data)->addFriend( $friend );
				return $Message;
			}
		}catch (\Exception $e){
			return OutMsg::outAbnormalMsg( $e->getMessage() );
		}
	}

}