<?php
/**
 * Created by PhpStorm.
 * User: Admin
 * Date: 2019/6/21
 * Time: 10:37
 */
namespace app\forum\controller;
use app\forum\model\IndexModel;
use think\Controller;
use think\facade\Request;
use app\forum\Traits\User;
use app\forum\Traits\Note;

class Index extends Controller{

	/**
	 * @var $data
	 * 用户信息
	 */
	protected $data;

	/**
	 * @var $model
	 * 公共模型
	 */
	protected $model;

	/**
	 * 初始化
	 */
	public function initialize()
	{
		parent::initialize(); // TODO: Change the autogenerated stub
		try{
			$data = User::dataInfo();
			$this->model = new IndexModel($data);
			$this->data = $data;
		}catch (\Exception $e){
			$this->error( $e->getMessage() );
		}

	}

	/**
	 * @return IndexModel
	 * @throws \Exception
	 */
	public function model(){
		return new IndexModel($this->data);
	}

	public function index(){
		try{
			$this->model = $this->model();
			$arrIfy = Note::classify();
			switch (Request()){
				case Request::isGet():
					$classify = input('get.classify');
					$this->model->index( $classify );break;
				case Request::isPost():
					$title = input('post.title');
					$this->model->search($title);break;
				default:$this->error("找不到此页面!");break;
			}
			return view('index',[
				'classify' => $arrIfy,
				'data'  =>  $this->data
			]);
		}catch (\Exception $e){
			$this->error( $e->getMessage() );
		}
	}
}
