<?php
/**
 * Created by PhpStorm.
 * User: Admin
 * Date: 2019/6/21
 * Time: 10:37
 */
namespace app\forum\controller;
use app\forum\model\IndexModel;
use app\forum\Traits\CURD;
use think\Controller;
use think\facade\Request;
use app\forum\Traits\User;
use app\forum\Traits\Note;

class Index extends Controller{

	/**
	 * @var $data
	 * 用户信息
	 */
	protected $data;

	/**
	 * @var $model
	 * 公共模型
	 */
	protected $model;

	/**
	 * @var $param
	 * 接收参数
	 */
	protected $param;

	/**
	 * @var array
	 */
	protected $map = [];

	/**
	 * 初始化
	 */
	public function initialize()
	{
		parent::initialize(); // TODO: Change the autogenerated stub
		try{
			$data = User::dataInfo();
			$this->model = new IndexModel($data);
			$this->data = $data;
			$this->param = CURD::PurificationParam();
			$this->map = ['is_show' => 1];
		}catch (\Exception $e){
			$this->error( $e->getMessage() );
		}

	}

	/**
	 * @param $data
	 * @return IndexModel
	 * @throws \Exception
	 *
	 */
	public function model($data){
		return new IndexModel($data);
	}

	/**
	 * @return \think\response\View
	 */
	public function index(){
		try{
			$arrIfy = Note::classify($this->map);
			$index = $this->model($this->data)->index();
			return view('index',[
				'classify' => $arrIfy,
				'data'  =>  $this->data,
				'index' =>  $index
			]);
		}catch (\Exception $e){
			$this->error( $e->getMessage() );
		}
	}


	/**
	 * @return \think\response\Json
	 * @throws \Exception
	 */
	public function lists(){
		if (Request::isGet()){
			$classify = $this->param;
			$lists = $this->model($this->data)->lists($classify);
			$lists == [] ? []:$lists;
			return $lists;
		}
	}

	/**
	 * @return mixed|void
	 * @throws \Exception
	 */
	public function search(){
		if (Request::isPost()){
			$title = $this->param;
			$lists = $this->model($this->data)->search($title);
		}else{
			$lists = [];
		}
		return $lists;
	}
}
