<?php
/**
 * Created by PhpStorm.
 * User: Admin
 * Date: 2019/6/21
 * Time: 16:21
 */
namespace app\forum\controller;
use app\forum\model\NoteModel;
use think\Controller;
use think\facade\Request;

class Note extends Controller {

	/**
	 * @var $model
	 * 公共模型
	 */
	protected $model;

	/**
	 * @var $data
	 * 用户信息
	 */
	protected $data;

	/**
	 * 初始化
	 */
	public function initialize()
	{
		parent::initialize(); // TODO: Change the autogenerated stub
		try{
			$data = \User::dataInfo();
			$this->model = new NoteModel( $data );
			$this->data = $data;
		}catch (\Exception $e){
			$this->error( $e->getMessage() );
		}
	}

	/**
	 * @return NoteModel
	 * @throws \Exception
	 */
	public function model(){
		return new NoteModel( \User::dataInfo() );
	}

	/**
	 * @return \think\response\View
	 * 帖子详情
	 */
	public function note(){
		try{
			$this->model = $this->model();
			if(Request::isGet()){
				$id = input('get.id',0,'intval');
				$noteInfo = $this->model->note( $id );
				return view('note',[
					'note'  =>  $noteInfo
				]);
			}else{
				$this->error('参数错误!');
			}
		}catch (\Exception $e){
			$this->error( $e->getMessage() );
		}
	}

	public function addNote( ){
		try{
			$this->model = $this->model();
			if (Request::isPost()){
				$data = input('post.');
				$this->model->addNote( $data );
			}
			return view('addNote');
		}catch (\Exception $e){
			return json_decode( $e->getMessage(),true);
		}
	}

}