<?php
/**
 * Created by PhpStorm.
 * User: Admin
 * Date: 2019/6/21
 * Time: 16:21
 */
namespace app\forum\controller;
use app\forum\model\NoteModel;
use app\forum\Traits\OutMsg;
use think\Controller;
use think\facade\Request;
use app\forum\Traits\User;

class Note extends Controller {
	/**
	 * 帖子操作控制器
	 */

	/**
	 * @var $model
	 * 公共模型
	 */
	protected $model;

	/**
	 * @var $data
	 * 用户信息
	 */
	protected $data;

	/**
	 * 初始化
	 */
	public function initialize()
	{
		parent::initialize(); // TODO: Change the autogenerated stub
		try{
			$data = User::dataInfo();
			$this->model = new NoteModel( $data );
			$this->data = $data;
		}catch (\Exception $e){
			$this->error( $e->getMessage() );
		}
	}

	/**
	 * @return NoteModel
	 * @throws \Exception
	 */
	public function model(){
		return new NoteModel( User::dataInfo() );
	}

	/**
	 * @return \think\response\View
	 * 帖子详情
	 */
	public function note(){
		try{
			$this->model = $this->model();
			if(Request::isGet()){
				$id = input('get.id',0,'intval');
				$noteInfo = $this->model->note( $id );
				return view('note',[
					'note'  =>  $noteInfo
				]);
			}else{
				$this->error('参数错误!');
			}
		}catch (\Exception $e){
			$this->error( $e->getMessage() );
		}
	}

	/**
	 * return mixed|\think\response\View
	 * @throws \Exception
	 * 发布帖子
	 */
	public function addNote(){
		try{
			$this->model = $this->model();
			if (Request::isPost()){
				$data = json_decode(file_get_contents('php://input'),true);
				$msg = $this->model->addNote( $data );
				return $msg;
			}
			return view('addNote');
		}catch (\Exception $e){
			return OutMsg::outAbnormalMsg( $e->getMessage() );
		}
	}

	/**
	 * @return mixed|\think\response\Json|\think\response\View
	 * @throws \Exception
	 * 编辑帖子
	 */
	public function editNote(){
		try{
			$this->model = $this->model();
			$noteInfo = "";
			if (Request::isGet()){
				$id = trim(input('get.id'));
				$noteInfo = $this->model->superInfo($id,null);
			}elseif (Request::isPost()){
				$data = json_decode(file_get_contents('php://input'),true);
				$msg = $this->model->editNote( $data );
				return $msg;
			}
			return view('editNote',[
				'noteInfo' => $noteInfo
			]);
		}catch (\Exception $e){
			return OutMsg::outAbnormalMsg( $e->getMessage() );
		}
	}

	/**
	 * @return mixed|\think\response\Json
	 * @throws \Exception
	 * 删除帖子
	 */
	public function del(){
		try{
			$this->model = $this->model();
			if (Request::isGet()){
				$id = input('get.id');
				$msg = $this->model->del( $id );
				return $msg;
			}
		}catch (\Exception $e){
			return OutMsg::outAbnormalMsg( $e->getMessage() );
		}
	}

	/**
	 * @return \think\response\Json
	 * @throws \Exception
	 */
	public function content(){
		try{
			if (Request::isPost()){
				$data = input('post');
			}
		}catch (\Exception $e){
			return OutMsg::outAbnormalMsg( $e->getMessage() );
		}
	}

	public function good(){

	}

	public function report(){

	}

}