<?php
/**
 * Created by PhpStorm.
 * User: Admin
 * Date: 2019/7/13
 * Time: 11:26
 */
namespace app\forum\controller;
use app\forum\model\TaskModel;
use app\forum\Traits\CURD;
use app\forum\Traits\OutMsg;
use app\forum\Traits\User;
use app\forum\Traits\Note;
use think\facade\Request;

class Task extends Base{

	/**
	 * @var $data
	 * 用户信息
	 */
	protected $data;

	/**
	 * @var $model
	 * 公共模型
	 */
	protected $model;

	/**
	 * @var $classify
	 * 分类
	 */
	protected $classify;

	/**
	 * @var $param
	 * 接收参数
	 */
	protected $param;

	/**
	 * 初始化
	 */
	public function initialize()
	{
		parent::initialize(); // TODO: Change the autogenerated stub
		try{
			$data = User::dataInfo();
			$this->model = new TaskModel($data);
			$this->data = $data;
			$this->classify = Note::classify();
			$this->param = CURD::PurificationParam();
		}catch (\Exception $e){
			$this->error( $e->getMessage() );
		}
	}

	/**
	 * @param $data
	 * @return TaskModel
	 * @throws \Exception
	 */
	public function model($data){
		return new TaskModel($data);
	}

	/**
	 * @return \think\response\View
	 * 任务首页
	 */
	public function index(){
		try{
			return view('index',[
				'classify'  =>  $this->classify,
				'data'  =>  $this->data,
				'title' =>  '今日任务'
			]);
		}catch (\Exception $e){
			$this->error( $e->getMessage() );
		}
	}

	/**
	 * @return mixed|\think\response\Json
	 * @throws \Exception
	 * 任务列表
	 */
	public function task(){
		try{
			if (Request::isGet()){
				$task = $this->model($this->data)->task();   //任务完成度
				return $task;
			}
		}catch (\Exception $e){
			return OutMsg::outAbnormalMsg( $e->getMessage() );
		}
	}


	public function getReward(){
		try{
			if(Request()->isGet()){
				$this->model($this->data)->getReward();
			}
		}catch (\Exception $e){
			return json_decode( $e->getMessage() ,true);
		}
	}
}