<?php

namespace app\factory\controller;

use app\factory\common\Param;
use app\factory\service\Hero;
use think\Controller as BaseController;

class Controller extends BaseController
{

	public $fetch;

	public $param;

	public $hero;

	/**
	 * 实例化英雄池
	 * Controller constructor.
	 * @param Hero $hero
	 */
	public function __construct(Hero $hero) {
		$this->hero = $hero;
	}

	public function initialize() {
		parent::initialize(); // TODO: Change the autogenerated stub
		$this->param = Param::PurificationGetFetchParam();
		$this->fetch = Param::PurificationPostFetchParam();
	}
}